server:
  port: 1024
  servlet:
    context-path: /wzg
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: root
    url: jdbc:mysql://localhost:3306/meituan?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&autoReconnect=true&useSSL=false&characterEncoding=utf-8
#    password: 123456
#    url: jdbc:mysql://42.194.130.239:3306/meituan?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&autoReconnect=true&useSSL=false&characterEncoding=utf-8
  redis:
    host: 127.0.0.1
    port: 6379
    username:
    password: root
    database: 0 #redis数据库索引（默认为0）
    jedis:
      pool:
        max-active: 50 #jedis连接池最大连接数（负值为没有限制）
        max-wait: 3000 #jedis连接池最大阻塞等待时间（负值为没有限制）
        max-idle: 20 #Jedis连接池中的最大空闲连接数
        min-idle: 2 #Jedis连接池中的最小空闲连接数
    timeout: 5000 #连接超时时间（毫秒）
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: true
#    fetchRegister: false
#serviceUrl:
#  defaultZone: http://${eureka.instance.hostname}:${1024}/eureka/
file:
  #path: /app/file/   #容器目录
   path: /            #本地目录