server:
  port: 1024
  servlet:
    context-path: /wzg
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/meituan?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&autoReconnect=true&useSSL=false&characterEncoding=utf-8
    password: 123456
    url: jdbc:mysql://42.194.130.239:3306/meituan?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&autoReconnect=true&useSSL=false&characterEncoding=utf-8

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: true
#    fetchRegister: false
#serviceUrl:
#  defaultZone: http://${eureka.instance.hostname}:${1024}/eureka/